### Individual Homework

#### Enter your name here: Péter Ferencz

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Analysis of movies IMDB dataset**

We will look at a ***subset*** sample of movies, taken from the [Kaggle IMDB 5000 movie dataset](https://www.kaggle.com/carolzhangdc/imdb-5000-movie-dataset)

In [2]:
movies = pd.read_csv('../Data/movies.csv')
movies

,title,genre,director,year,duration,gross,budget,cast_facebook_likes,votes,reviews,rating
0,Avatar,Action,James Cameron,2009,178,760505847,237000000,4834,886204,3777,7.9
1,Titanic,Drama,James Cameron,1997,194,658672302,200000000,45223,793059,2843,7.7
2,Jurassic World,Action,Colin Trevorrow,2015,124,652177271,150000000,8458,418214,1934,7.0
3,The Avengers,Action,Joss Whedon,2012,173,623279547,220000000,87697,995415,2425,8.1
4,The Dark Knight,Action,Christopher Nolan,2008,152,533316061,185000000,57802,1676169,5312,9.0
...,...,...,...,...,...,...,...,...,...,...,...
2956,Locker 13,Thriller,Bruce Dellis,2014,95,2468,300000,2048,241,15,4.8
2957,The Ghastly Love of Johnny X,Comedy,Paul Bunnell,2012,106,2436,2000000,1611,344,113,5.7
2958,Detention of the Dead,Comedy,Alex Craig Mann,2012,87,1332,500000,2251,2038,49,4.6
2959,The Trials of Darryl Hunt,Crime,Ricki Stern,2006,106,1111,200000,2,771,21,7.7
2960,The Jimmy Show,Comedy,Frank Whaley,2001,96,703,1500000,920,480,30,5.4

Besides the obvious variables of `title`, `genre`, `director`, `year`, and `duration`, the rest of the variables are as follows:

-   `gross` : The gross earnings in the US box office, not adjusted for inflation
-   `budget`: The movie's budget
-   `cast_facebook_likes`: the number of facebook likes cast memebrs received
-   `votes`: the number of people who voted for (or rated) the movie in IMDB
-   `reviews`: the number of reviews for that movie
-   `rating`: IMDB average rating

**Produce a table with the count of movies by genre, ranked in descending order**

In [5]:
movie_count_per_genre = (
    movies
    .groupby('genre')
    .agg(
        count=('title', 'size')
    )
    .reset_index()
    .sort_values('count', ascending=False)
)

display(movie_count_per_genre)

          genre  count
4        Comedy    848
0        Action    738
7         Drama    498
1     Adventure    288
5         Crime    202
3     Biography    135
10       Horror    131
2     Animation     35
9       Fantasy     28
6   Documentary     25
12      Mystery     16
14       Sci-Fi      7
8        Family      3
11      Musical      2
13      Romance      2
16      Western      2
15     Thriller      1

**Produce a table with the average gross earning and budget (`gross` and `budget`) by genre. Calculate a variable `return_on_budget` which shows how many \$ did a movie make at the box office for each \$ of its budget. Ranked genres by this `return_on_budget` in descending order**

In [18]:
#Since I didn't understand clearly from the task that we should do the mean calculation before the group by or after, I decided to provide all the solutions.

# return_on_budget calculated per movie and the average calculation comes next
genre_rank_by_return = (
    movies
    .assign(
        return_on_budget=movies['gross'] / movies['budget']
    )
    .groupby('genre')
    .agg(
        return_on_budget_mean= ('return_on_budget', 'mean')
    )
    .reset_index()
    .sort_values('return_on_budget_mean', ascending=False)
)

display(genre_rank_by_return)

          genre  return_on_budget_mean
10       Horror              88.304785
3     Biography              22.280597
11      Musical              18.817819
8        Family              14.076490
6   Documentary               8.698550
16      Western               7.062800
9       Fantasy               6.681969
2     Animation               5.009095
4        Comedy               3.713990
12      Mystery               3.269397
13      Romance               3.168112
7         Drama               2.946105
1     Adventure               2.411706
5         Crime               2.174751
0        Action               1.920877
14       Sci-Fi               1.580394
15     Thriller               0.008227

In [ ]:
# the gross and budget means are calculated first, after that the reutrn_on_budget

genre_rank_by_return_2 = (
    movies
    .groupby('genre')
    .agg(
        gross_mean=('gross', 'mean'),
        budget_mean=('budget', 'mean'),
    )
    .assign(
        return_on_budget=lambda df: df['gross_mean'] / df['budget_mean']
    )
    .reset_index()
    .sort_values('return_on_budget', ascending=False)[['genre', 'return_on_budget']]
)

display(genre_rank_by_return_2)

          genre  return_on_budget
11      Musical         28.870983
8        Family         10.055763
16      Western          6.009202
6   Documentary          2.947420
10       Horror          2.792593
9       Fantasy          2.412040
4        Comedy          1.743843
12      Mystery          1.721958
2     Animation          1.595324
3     Biography          1.583600
1     Adventure          1.445077
7         Drama          1.427637
5         Crime          1.410068
13      Romance          1.245239
0        Action          1.213426
14       Sci-Fi          1.079010
15     Thriller          0.008227

**Produce a table that shows the top 15 directors who have created the highest gross revenue in the box office. Don't just show the total gross amount, but also the mean, median, and standard deviation per director**

In [ ]:
top_directors = (
    movies
    .
)

**Produce a table that describes how ratings are distributed by genre. We don't want just the mean, but also, min, max, median, SD and some kind of a histogram or density graph that visually shows how ratings are distributed.**

**Challenge - Produce a table of your own choosing, something you think is important/interesting to have data for, justify your result by writting a 2 sentence explanation/interpretation of the result.**

#### Use visualisation to answer the following questions

**Examine the relationship between `gross` and `cast_facebook_likes`. Produce a scatterplot and write one sentence discussing whether the number of facebook likes that the cast has received is likely to be a good predictor of how much money a movie will make at the box office. What variable are you going to map to the Y- and X- axes?**

**Examine the relationship between `gross` and `budget`. Produce a scatterplot and write one sentence discussing whether budget is likely to be a good predictor of how much money a movie will make at the box office.**

**Examine the relationship between `gross` and `rating`. Produce a scatterplot, faceted by `genre` and discuss whether IMDB ratings are likely to be a good predictor of how much money a movie will make at the box office. Is there anything strange in this dataset?**

**Challenge - Produce a visualisation of your choosing, something you think is important to explore/investigate visually. Do make it a comprehensive graph and not a single histogram or density plot. Make it publication ready, label your axes, give it a title, choose colouring options, appropirately formatted text etc.**

### Deliverables

Poduce a clean, stand-alone notebook (or HTML export) with:

All tables/plots properly labeled

Brief interpretations where requested

Upload final HTML/Notebook.